---
read_csv: # https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html
  skiprows: 0
  skipfooter: 0
  engine: 'python' # {‘c’, ‘python’, ‘pyarrow’}
  encoding: 'latin-1' # utf-8, latin-1 https://docs.python.org/3/library/codecs.html#standard-encodings
  quotechar: '"'
  on_bad_lines: 'warn' # {‘error’, ‘warn’, ‘skip’}
  dtype: 'str'
  keep_default_na: false
