name: Weekly Build

on:
  schedule:
    # This is ignored when running locally but defines the schedule if running in GitHub
    - cron: "0 0 * * 1"

  workflow_dispatch: # Allows manual triggers

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Build the package
      run: python setup.py sdist bdist_wheel

    - name: Run tests
      run: pytest

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: dist/
